-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Query exposing (..)

import Api.InputObject
import Api.Interface
import Api.Object
import Api.Scalar
import Api.ScalarCodecs
import Api.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode exposing (Decoder)


type alias GetQuestionRequiredArguments =
    { id : Api.ScalarCodecs.Id }


getQuestion :
    GetQuestionRequiredArguments
    -> SelectionSet decodesTo Api.Object.Question
    -> SelectionSet (Maybe decodesTo) RootQuery
getQuestion requiredArgs____ object____ =
    Object.selectionForCompositeField "getQuestion" [ Argument.required "id" requiredArgs____.id (Api.ScalarCodecs.codecs |> Api.Scalar.unwrapEncoder .codecId) ] object____ (Basics.identity >> Decode.nullable)


type alias ListQuestionsOptionalArguments =
    { filter : OptionalArgument Api.InputObject.ModelQuestionFilterInput
    , limit : OptionalArgument Int
    , nextToken : OptionalArgument String
    }


listQuestions :
    (ListQuestionsOptionalArguments -> ListQuestionsOptionalArguments)
    -> SelectionSet decodesTo Api.Object.ModelQuestionConnection
    -> SelectionSet (Maybe decodesTo) RootQuery
listQuestions fillInOptionals____ object____ =
    let
        filledInOptionals____ =
            fillInOptionals____ { filter = Absent, limit = Absent, nextToken = Absent }

        optionalArgs____ =
            [ Argument.optional "filter" filledInOptionals____.filter Api.InputObject.encodeModelQuestionFilterInput, Argument.optional "limit" filledInOptionals____.limit Encode.int, Argument.optional "nextToken" filledInOptionals____.nextToken Encode.string ]
                |> List.filterMap Basics.identity
    in
    Object.selectionForCompositeField "listQuestions" optionalArgs____ object____ (Basics.identity >> Decode.nullable)
